" Install vim-plug if not already installed.
if empty(glob('~/.vim/autoload/plug.vim'))
	silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
			\ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


call plug#begin()

Plug 'majutsushi/tagbar', { 'on': 'Tagbar' }

Plug 'scrooloose/nerdtree', { 'on': 'NERDTree' }
Plug 'scrooloose/syntastic'

function! BuildYCM(info)
	if a:info.status == 'installed' || a:info.force
		!./install.py --clang-completer
	endif
endfunction
Plug 'Valloric/YouCompleteMe', { 'for': ['c', 'cpp'], 'do': function('BuildYCM') }

call plug#end()

set autoindent
set encoding=utf-8
set noexpandtab
set number
set scrolloff=5
set shiftwidth=4
set smartindent
set tabstop=4

function! s:statusline_expr()
	let mod = "%{&modified ? '[+] ' : !&modifiable ? '[x] ' : ''}"
	let ro  = "%{&readonly ? '[RO] ' : ''}"
	let ft  = "%{len(&filetype) ? '['.&filetype.'] ' : ''}"
	let fug = "%{exists('g:loaded_fugitive') ? fugitive#statusline() : ''}"
	let sep = ' %= '
	let pos = ' %-12(%l : %c%V%) '
	let pct = ' %P'

	return '[%n] %F %<'.mod.ro.ft.fug.sep.pos.'%*'.pct
endfunction
let &statusline = s:statusline_expr()

silent! set ttymouse=xterm2
set mouse=a

filetype on

