export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="frisk"

COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(archlinux colored-man-pages colorize git)

source $ZSH/oh-my-zsh.sh

# vim: set syntax=zsh

